require 'modules.positions'
require 'modules.hud_cache'

function init(self)

end

function on_message(self, message_id, message, sender)
	if 
		message_id == hash('trigger_response') 
	and
		message.other_group == hash('mage')
	then
		mage_has_key = true
		table.insert(
			messages, 
			1, 
			{
				'Hum... A key! I wonder what it open!',
				hash('general_message')
			}
		)
		go.delete()
	end
end
