require 'modules.shared'

go.property('sprite', hash(''))
go.property('destination', hash(''))
go.property('destiny_position', vmath.vector3())
require 'modules.positions'

function init(self)
	sprite_anim(self.sprite)
end


function on_message(self, message_id, message, sender)
	if message_id == hash('trigger_response') and message.other_group == hash('mage') then
		triger_level_load(self.destination)
		mage_spawn_position = self.destiny_position
	end
end